# installing the required library

In [1]:
pip install requests pandas

Requirement already satisfied: requests in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.34.2)
Requirement already satisfied: pandas in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2026.6.17)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\SAMSUNG\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

Store your API key safely

Since you're going to upload this project to GitHub, do not write this:

API_KEY = "your_actual_api_key"

Instead, we'll use an environment variable.

In [3]:
import os

os.environ["OPENWEATHER_API_KEY"] = "6518cc1b6508c85bd2a8d7b3eb4fc094"

# Test the API

In [4]:
import os
import requests

API_KEY = os.environ["OPENWEATHER_API_KEY"]

city = "Lagos"

url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "q": city,
    "appid": API_KEY,
    "units": "metric"
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)

if response.status_code == 200:
    print("API connection successful!")
    print(response.json())
else:
    print(response.json())

Status code: 200
API connection successful!
{'coord': {'lon': 3.75, 'lat': 6.5833}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 26.02, 'feels_like': 26.02, 'temp_min': 26.02, 'temp_max': 26.02, 'pressure': 1016, 'humidity': 85, 'sea_level': 1016, 'grnd_level': 1016}, 'visibility': 10000, 'wind': {'speed': 2.9, 'deg': 253, 'gust': 5.64}, 'clouds': {'all': 100}, 'dt': 1787470285, 'sys': {'country': 'NG', 'sunrise': 1787463547, 'sunset': 1787507800}, 'timezone': 3600, 'id': 2332453, 'name': 'Lagos', 'cod': 200}

# Extracting Data for Cities

In [5]:
locations = [

    # NORTH CENTRAL
    ("Benue", "Makurdi", "North Central"),
    ("Kogi", "Lokoja", "North Central"),
    ("Kwara", "Ilorin", "North Central"),
    ("Nasarawa", "Lafia", "North Central"),
    ("Niger", "Minna", "North Central"),
    ("Plateau", "Jos", "North Central"),
    ("FCT", "Abuja", "North Central"),

    # NORTH EAST
    ("Adamawa", "Yola", "North East"),
    ("Bauchi", "Bauchi", "North East"),
    ("Borno", "Maiduguri", "North East"),
    ("Gombe", "Gombe", "North East"),
    ("Taraba", "Jalingo", "North East"),
    ("Yobe", "Damaturu", "North East"),

    # NORTH WEST
    ("Jigawa", "Dutse", "North West"),
    ("Kaduna", "Kaduna", "North West"),
    ("Kano", "Kano", "North West"),
    ("Katsina", "Katsina", "North West"),
    ("Kebbi", "Birnin Kebbi", "North West"),
    ("Sokoto", "Sokoto", "North West"),
    ("Zamfara", "Gusau", "North West"),

    # SOUTH EAST
    ("Abia", "Umuahia", "South East"),
    ("Anambra", "Awka", "South East"),
    ("Ebonyi", "Abakaliki", "South East"),
    ("Enugu", "Enugu", "South East"),
    ("Imo", "Owerri", "South East"),

    # SOUTH SOUTH
    ("Akwa Ibom", "Uyo", "South South"),
    ("Bayelsa", "Yenagoa", "South South"),
    ("Cross River", "Calabar", "South South"),
    ("Delta", "Asaba", "South South"),
    ("Edo", "Benin City", "South South"),
    ("Rivers", "Port Harcourt", "South South"),

    # SOUTH WEST
    ("Ekiti", "Ado-Ekiti", "South West"),
    ("Lagos", "Ikeja", "South West"),
    ("Ogun", "Abeokuta", "South West"),
    ("Ondo", "Akure", "South West"),
    ("Osun", "Osogbo", "South West"),
    ("Oyo", "Ibadan", "South West")
]

print("Number of locations:", len(locations))

Number of locations: 37

# Creating a structured table

In [6]:
weather_data = []

for state, city, zone in locations:

    params = {
        "q": f"{city},NG",
        "appid": API_KEY,
        "units": "metric"
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:

        data = response.json()

        weather_data.append({
            "State": state,
            "City": city,
            "Geopolitical_Zone": zone,
            "Temperature_C": data["main"]["temp"],
            "Feels_Like_C": data["main"]["feels_like"],
            "Humidity_%": data["main"]["humidity"],
            "Pressure_hPa": data["main"]["pressure"],
            "Wind_Speed_mps": data["wind"]["speed"],
            "Weather": data["weather"][0]["description"]
        })

        print(f"{state}: data extracted successfully")

    else:
        print(f"{state}: failed - status code {response.status_code}")

Benue: data extracted successfully
Kogi: data extracted successfully
Kwara: data extracted successfully
Nasarawa: data extracted successfully
Niger: data extracted successfully
Plateau: data extracted successfully
FCT: data extracted successfully
Adamawa: data extracted successfully
Bauchi: data extracted successfully
Borno: data extracted successfully
Gombe: data extracted successfully
Taraba: data extracted successfully
Yobe: data extracted successfully
Jigawa: data extracted successfully
Kaduna: data extracted successfully
Kano: data extracted successfully
Katsina: data extracted successfully
Kebbi: data extracted successfully
Sokoto: data extracted successfully
Zamfara: data extracted successfully
Abia: data extracted successfully
Anambra: data extracted successfully
Ebonyi: data extracted successfully
Enugu: data extracted successfully
Imo: data extracted successfully
Akwa Ibom: data extracted successfully
Bayelsa: data extracted successfully
Cross River: data extracted successfully
Delta: data extracted successfully
Edo: data extracted successfully
Rivers: data extracted successfully
Ekiti: data extracted successfully
Lagos: data extracted successfully
Ogun: data extracted successfully
Ondo: data extracted successfully
Osun: data extracted successfully
Oyo: data extracted successfully

In [7]:
weather_df = pd.DataFrame(weather_data)

# Data Validation

In [8]:
weather_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              37 non-null     str
 1   City               37 non-null     str
 2   Geopolitical_Zone  37 non-null     str
 3   Temperature_C      37 non-null     float64
 4   Feels_Like_C       37 non-null     float64
 5   Humidity_%         37 non-null     int64
 6   Pressure_hPa       37 non-null     int64
 7   Wind_Speed_mps     37 non-null     float64
 8   Weather            37 non-null     str
dtypes: float64(3), int64(2), str(4)
memory usage: 2.7 KB

In [9]:
weather_df.isnull().sum()

State                0
City                 0
Geopolitical_Zone    0
Temperature_C        0
Feels_Like_C         0
Humidity_%           0
Pressure_hPa         0
Wind_Speed_mps       0
Weather              0
dtype: int64

In [10]:
weather_df.describe()

       Temperature_C  Feels_Like_C  Humidity_%  Pressure_hPa  Wind_Speed_mps
count      37.000000     37.000000   37.000000     37.000000       37.000000
mean       25.405676     26.532162   82.621622   1016.216216        2.190270
std         2.025038      2.425159   14.089696      0.786523        1.150127
min        20.830000     21.160000   48.000000   1014.000000        0.340000
25%        24.140000     25.060000   70.000000   1016.000000        1.400000
50%        25.010000     25.940000   90.000000   1016.000000        1.980000
75%        26.930000     28.640000   94.000000   1017.000000        2.840000
max        30.870000     32.030000   97.000000   1018.000000        5.480000

In [11]:
weather_df.columns

Index(['State', 'City', 'Geopolitical_Zone', 'Temperature_C', 'Feels_Like_C',
       'Humidity_%', 'Pressure_hPa', 'Wind_Speed_mps', 'Weather'],
      dtype='str')

In [12]:
weather_df["Geopolitical_Zone"].value_counts()

Geopolitical_Zone
North Central    7
North West       7
North East       6
South South      6
South West       6
South East       5
Name: count, dtype: int64

# Load the Transformed Data

In [13]:
weather_df.to_csv("weather_data.csv", index=False)

print("Weather dataset saved successfully!")

Weather dataset saved successfully!

# Sorting data

In [14]:
zone_order = [
    "North Central",
    "North East",
    "North West",
    "South East",
    "South South",
    "South West"
]

weather_df["Geopolitical_Zone"] = pd.Categorical(
    weather_df["Geopolitical_Zone"],
    categories=zone_order,
    ordered=True
)

weather_df = weather_df.sort_values(
    ["Geopolitical_Zone", "State"]
).reset_index(drop=True)

weather_df

,State,City,Geopolitical_Zone,Temperature_C,Feels_Like_C,Humidity_%,Pressure_hPa,Wind_Speed_mps,Weather
0,Benue,Makurdi,North Central,25.79,26.75,89,1016,2.49,overcast clouds
1,FCT,Abuja,North Central,23.45,24.28,93,1017,0.34,overcast clouds
2,Kogi,Lokoja,North Central,25.59,26.50,88,1016,1.04,overcast clouds
3,Kwara,Ilorin,North Central,24.00,24.81,90,1016,3.07,moderate rain
4,Nasarawa,Lafia,North Central,24.99,25.95,92,1016,0.84,overcast clouds
5,Niger,Minna,North Central,24.61,25.48,90,1016,1.44,overcast clouds
6,Plateau,Jos,North Central,20.83,21.16,84,1018,0.55,overcast clouds
7,Adamawa,Yola,North East,27.03,28.74,68,1016,1.31,overcast clouds
8,Bauchi,Bauchi,North East,27.18,28.64,64,1016,2.52,overcast clouds
9,Borno,Maiduguri,North East,30.87,32.03,48,1014,4.56,broken clouds
10,Gombe,Gombe,North East,27.52,29.15,64,1016,3.33,broken clouds
11,Taraba,Jalingo,North East,26.97,29.40,77,1016,1.33,broken clouds
12,Yobe,Damaturu,North East,29.68,31.53,56,1014,5.48,scattered clouds
13,Jigawa,Dutse,North West,26.37,26.37,62,1016,2.53,overcast clouds
14,Kaduna,Kaduna,North West,25.06,25.68,79,1017,1.40,overcast clouds
15,Kano,Kano,North West,26.80,27.71,58,1016,2.07,overcast clouds
16,Katsina,Katsina,North West,27.91,29.65,63,1016,2.99,overcast clouds
17,Kebbi,Birnin Kebbi,North West,27.56,30.18,73,1016,3.99,scattered clouds
18,Sokoto,Sokoto,North West,28.51,31.07,66,1015,3.45,overcast clouds
19,Zamfara,Gusau,North West,26.93,28.74,70,1016,4.00,overcast clouds
20,Abia,Umuahia,South East,24.66,25.53,90,1017,1.92,moderate rain
21,Anambra,Awka,South East,24.73,25.66,92,1017,1.83,heavy intensity rain
22,Ebonyi,Abakaliki,South East,24.29,25.26,95,1017,1.98,overcast clouds
23,Enugu,Enugu,South East,24.14,25.06,94,1017,2.49,moderate rain
24,Imo,Owerri,South East,23.82,24.76,96,1017,0.83,light rain
25,Akwa Ibom,Uyo,South South,23.60,24.50,95,1017,2.30,moderate rain
26,Bayelsa,Yenagoa,South South,23.75,24.69,96,1016,1.89,light rain
27,Cross River,Calabar,South South,24.47,25.43,94,1017,1.85,light rain
28,Delta,Asaba,South South,25.22,26.17,91,1016,1.76,moderate rain
29,Edo,Benin City,South South,25.01,25.94,91,1016,1.22,moderate rain
30,Rivers,Port Harcourt,South South,24.17,25.10,94,1016,0.58,overcast clouds
31,Ekiti,Ado-Ekiti,South West,23.08,23.90,94,1017,2.12,overcast clouds
32,Lagos,Ikeja,South West,25.94,26.91,89,1016,3.09,overcast clouds
33,Ogun,Abeokuta,South West,25.08,25.99,90,1016,2.84,overcast clouds
34,Ondo,Akure,South West,23.46,24.32,94,1017,1.65,overcast clouds
35,Osun,Osogbo,South West,22.71,23.57,97,1016,1.57,moderate rain
36,Oyo,Ibadan,South West,24.23,25.08,91,1016,2.39,overcast clouds

# BUSINESS QUESTIONS

1. Which geopolitical zone has the highest average temperature?

In [15]:
zone_temperature = (
    weather_df.groupby("Geopolitical_Zone")["Temperature_C"]
    .mean()
    .sort_values(ascending=False)
)

zone_temperature

Geopolitical_Zone
North East       28.208333
North West       27.020000
South South      24.370000
South East       24.328000
North Central    24.180000
South West       24.083333
Name: Temperature_C, dtype: float64

2. Average Humidity by Zones

In [16]:
zone_humidity = (
    weather_df.groupby("Geopolitical_Zone")["Humidity_%"]
    .mean()
    .sort_values(ascending=False)
)

zone_humidity.round(2)

Geopolitical_Zone
South South      93.50
South East       93.40
South West       92.50
North Central    89.43
North West       67.29
North East       62.83
Name: Humidity_%, dtype: float64

3. Which states have the highest and lowest temperatures?

In [17]:
state_temperature = (
    weather_df[["State", "Geopolitical_Zone", "Temperature_C"]]
    .sort_values("Temperature_C", ascending=False)
)

state_temperature.head(10)

      State Geopolitical_Zone  Temperature_C
9     Borno        North East          30.87
12     Yobe        North East          29.68
18   Sokoto        North West          28.51
16  Katsina        North West          27.91
17    Kebbi        North West          27.56
10    Gombe        North East          27.52
8    Bauchi        North East          27.18
7   Adamawa        North East          27.03
11   Taraba        North East          26.97
19  Zamfara        North West          26.93

--- Lowest Temperature---

In [18]:
state_temperature.tail(10)

        State Geopolitical_Zone  Temperature_C
23      Enugu        South East          24.14
3       Kwara     North Central          24.00
24        Imo        South East          23.82
26    Bayelsa       South South          23.75
25  Akwa Ibom       South South          23.60
34       Ondo        South West          23.46
1         FCT     North Central          23.45
31      Ekiti        South West          23.08
35       Osun        South West          22.71
6     Plateau     North Central          20.83

In [19]:
hottest_state = state_temperature.iloc[0]

coolest_state = state_temperature.iloc[-1]

print(
    f"Hottest: {hottest_state['State']} "
    f"({hottest_state['Temperature_C']:.2f}°C)"
)

print(
    f"Coolest: {coolest_state['State']} "
    f"({coolest_state['Temperature_C']:.2f}°C)"
)

Hottest: Borno (30.87°C)
Coolest: Plateau (20.83°C)

4. Which states have the highest wind speeds?

In [20]:
state_wind = (
    weather_df[["State", "Geopolitical_Zone", "Wind_Speed_mps"]]
    .sort_values("Wind_Speed_mps", ascending=False)
)

state_wind.head(10)

      State Geopolitical_Zone  Wind_Speed_mps
12     Yobe        North East            5.48
9     Borno        North East            4.56
19  Zamfara        North West            4.00
17    Kebbi        North West            3.99
18   Sokoto        North West            3.45
10    Gombe        North East            3.33
32    Lagos        South West            3.09
3     Kwara     North Central            3.07
16  Katsina        North West            2.99
33     Ogun        South West            2.84

5. Which states have the highest combination of heat and humidity?

In [21]:
heat_humidity = (
    weather_df[[
        "State",
        "Geopolitical_Zone",
        "Temperature_C",
        "Humidity_%"
    ]]
    .copy()
)

heat_humidity["Heat_Humidity_Score"] = (
    heat_humidity["Temperature_C"] * heat_humidity["Humidity_%"]
)

heat_humidity = heat_humidity.sort_values(
    "Heat_Humidity_Score",
    ascending=False
)

heat_humidity.head(10)

,State,Geopolitical_Zone,Temperature_C,Humidity_%,Heat_Humidity_Score
32,Lagos,South West,25.94,89,2308.66
22,Ebonyi,South East,24.29,95,2307.55
27,Cross River,South South,24.47,94,2300.18
4,Nasarawa,North Central,24.99,92,2299.08
0,Benue,North Central,25.79,89,2295.31
28,Delta,South South,25.22,91,2295.02
24,Imo,South East,23.82,96,2286.72
26,Bayelsa,South South,23.75,96,2280.00
29,Edo,South South,25.01,91,2275.91
21,Anambra,South East,24.73,92,2275.16

6. Geopolitical Zones that Show the Greatest Weather Variation

In [23]:
zone_temperature_range = (
    weather_df.groupby("Geopolitical_Zone")["Temperature_C"]
    .agg(["min", "max", "mean"])
)

zone_temperature_range["Temperature_Range"] = (
    zone_temperature_range["max"] - zone_temperature_range["min"]
)

zone_temperature_range.sort_values(
    "Temperature_Range",
    ascending=False
).round(2)

                     min    max   mean  Temperature_Range
Geopolitical_Zone
North Central      20.83  25.79  24.18               4.96
North East         26.97  30.87  28.21               3.90
North West         25.06  28.51  27.02               3.45
South West         22.71  25.94  24.08               3.23
South South        23.60  25.22  24.37               1.62
South East         23.82  24.73  24.33               0.91

In [24]:
most_variable_zone = zone_temperature_range["Temperature_Range"].idxmax()
largest_range = zone_temperature_range["Temperature_Range"].max()

print(
    f"{most_variable_zone} has the greatest temperature variation "
    f"with a range of {largest_range:.2f}°C."
)

North Central has the greatest temperature variation with a range of 4.96°C.

# Creating a Python ETL Pipeline

In [27]:
%%writefile weather_etl.py
import os
import requests
import pandas as pd
import time


# ============================================================
# 1. EXTRACT
# ============================================================

API_KEY = os.getenv("OPENWEATHER_API_KEY")

if not API_KEY:
    raise ValueError(
        "OPENWEATHER_API_KEY was not found. "
        "Please set your API key as an environment variable."
    )


# One representative city for each Nigerian state + FCT
locations = [
    # North Central
    ("Benue", "Makurdi", "North Central"),
    ("Kogi", "Lokoja", "North Central"),
    ("Kwara", "Ilorin", "North Central"),
    ("Nasarawa", "Lafia", "North Central"),
    ("Niger", "Minna", "North Central"),
    ("Plateau", "Jos", "North Central"),
    ("FCT", "Abuja", "North Central"),

    # North East
    ("Adamawa", "Yola", "North East"),
    ("Bauchi", "Bauchi", "North East"),
    ("Borno", "Maiduguri", "North East"),
    ("Gombe", "Gombe", "North East"),
    ("Taraba", "Jalingo", "North East"),
    ("Yobe", "Damaturu", "North East"),

    # North West
    ("Jigawa", "Dutse", "North West"),
    ("Kaduna", "Kaduna", "North West"),
    ("Kano", "Kano", "North West"),
    ("Katsina", "Katsina", "North West"),
    ("Kebbi", "Birnin Kebbi", "North West"),
    ("Sokoto", "Sokoto", "North West"),
    ("Zamfara", "Gusau", "North West"),

    # South East
    ("Abia", "Umuahia", "South East"),
    ("Anambra", "Awka", "South East"),
    ("Ebonyi", "Abakaliki", "South East"),
    ("Enugu", "Enugu", "South East"),
    ("Imo", "Owerri", "South East"),

    # South South
    ("Akwa Ibom", "Uyo", "South South"),
    ("Bayelsa", "Yenagoa", "South South"),
    ("Cross River", "Calabar", "South South"),
    ("Delta", "Asaba", "South South"),
    ("Edo", "Benin City", "South South"),
    ("Rivers", "Port Harcourt", "South South"),

    # South West
    ("Ekiti", "Ado-Ekiti", "South West"),
    ("Lagos", "Ikeja", "South West"),
    ("Ogun", "Abeokuta", "South West"),
    ("Ondo", "Akure", "South West"),
    ("Osun", "Osogbo", "South West"),
    ("Oyo", "Ibadan", "South West")
]


weather_data = []


for state, city, zone in locations:

    url = "https://api.openweathermap.org/data/2.5/weather"

    params = {
        "q": f"{city},NG",
        "appid": API_KEY,
        "units": "metric"
    }

    try:
        response = requests.get(url, params=params, timeout=10)

        if response.status_code == 200:

            data = response.json()

            weather_data.append({
                "City": city,
                "State": state,
                "Country": "Nigeria",
                "Geopolitical_Zone": zone,
                "Temperature_C": data["main"]["temp"],
                "Feels_Like_C": data["main"]["feels_like"],
                "Humidity_%": data["main"]["humidity"],
                "Pressure_hPa": data["main"]["pressure"],
                "Wind_Speed_mps": data["wind"]["speed"],
                "Weather": data["weather"][0]["description"]
            })

            print(f"{state}: data extracted successfully")

        else:
            print(
                f"{state}: extraction failed "
                f"(Status code: {response.status_code})"
            )

    except requests.exceptions.RequestException as error:
        print(f"{state}: request failed - {error}")

    # Prevent sending requests too quickly
    time.sleep(1)


# ============================================================
# 2. TRANSFORM
# ============================================================

weather_df = pd.DataFrame(weather_data)

print("\nData extracted:")
print(weather_df.head())


# Check for missing values
print("\nMissing values:")
print(weather_df.isnull().sum())


# Remove duplicate records if any
weather_df = weather_df.drop_duplicates()


# Sort by geopolitical zone and state
weather_df = weather_df.sort_values(
    ["Geopolitical_Zone", "State"]
).reset_index(drop=True)


print("\nFinal dataset:")
print(weather_df)


# ============================================================
# 3. LOAD
# ============================================================

weather_df.to_csv(
    "weather_data.csv",
    index=False
)

print("\nProcessed dataset saved successfully as weather_data.csv")

print("\nFinal dataset shape:")
print(weather_df.shape)

print("\nETL pipeline completed successfully.")

Writing weather_etl.py

In [28]:
!python weather_etl.py

Benue: data extracted successfully
Kogi: data extracted successfully
Kwara: data extracted successfully
Nasarawa: data extracted successfully
Niger: data extracted successfully
Plateau: data extracted successfully
FCT: data extracted successfully
Adamawa: data extracted successfully
Bauchi: data extracted successfully
Borno: data extracted successfully
Gombe: data extracted successfully
Taraba: data extracted successfully
Yobe: data extracted successfully
Jigawa: data extracted successfully
Kaduna: data extracted successfully
Kano: data extracted successfully
Katsina: data extracted successfully
Kebbi: data extracted successfully
Sokoto: data extracted successfully
Zamfara: data extracted successfully
Abia: data extracted successfully
Anambra: data extracted successfully
Ebonyi: data extracted successfully
Enugu: data extracted successfully
Imo: data extracted successfully
Akwa Ibom: data extracted successfully
Bayelsa: data extracted successfully
Cross River: data extracted successfully
Delta: data extracted successfully
Edo: data extracted successfully
Rivers: data extracted successfully
Ekiti: data extracted successfully
Lagos: data extracted successfully
Ogun: data extracted successfully
Ondo: data extracted successfully
Osun: data extracted successfully
Oyo: data extracted successfully

Data extracted:
      City     State  Country  ... Pressure_hPa  Wind_Speed_mps          Weather
0  Makurdi     Benue  Nigeria  ...         1016            2.25  overcast clouds
1   Lokoja      Kogi  Nigeria  ...         1016            1.22  overcast clouds
2   Ilorin     Kwara  Nigeria  ...         1016            3.41  overcast clouds
3    Lafia  Nasarawa  Nigeria  ...         1016            1.59  overcast clouds
4    Minna     Niger  Nigeria  ...         1016            1.34  overcast clouds

[5 rows x 10 columns]

Missing values:
City                 0
State                0
Country              0
Geopolitical_Zone    0
Temperature_C        0
Feels_Like_C         0
Humidity_%           0
Pressure_hPa         0
Wind_Speed_mps       0
Weather              0
dtype: int64

Final dataset:
             City        State  ... Wind_Speed_mps           Weather
0         Makurdi        Benue  ...           2.25   overcast clouds
1           Abuja          FCT  ...           0.33   overcast clouds
2          Lokoja         Kogi  ...           1.22   overcast clouds
3          Ilorin        Kwara  ...           3.41   overcast clouds
4           Lafia     Nasarawa  ...           1.59   overcast clouds
5           Minna        Niger  ...           1.34   overcast clouds
6             Jos      Plateau  ...           0.53     broken clouds
7            Yola      Adamawa  ...           1.50     broken clouds
8          Bauchi       Bauchi  ...           3.12   overcast clouds
9       Maiduguri        Borno  ...           4.90   overcast clouds
10          Gombe        Gombe  ...           4.06     broken clouds
11        Jalingo       Taraba  ...           1.91     broken clouds
12       Damaturu         Yobe  ...           5.31  scattered clouds
13          Dutse       Jigawa  ...           2.17   overcast clouds
14         Kaduna       Kaduna  ...           1.73   overcast clouds
15           Kano         Kano  ...           1.67   overcast clouds
16        Katsina      Katsina  ...           3.77   overcast clouds
17   Birnin Kebbi        Kebbi  ...           3.67  scattered clouds
18         Sokoto       Sokoto  ...           3.67   overcast clouds
19          Gusau      Zamfara  ...           2.65   overcast clouds
20        Umuahia         Abia  ...           2.40        light rain
21           Awka      Anambra  ...           1.62     moderate rain
22      Abakaliki       Ebonyi  ...           1.97   overcast clouds
23          Enugu        Enugu  ...           2.02   overcast clouds
24         Owerri          Imo  ...           2.09        light rain
25            Uyo    Akwa Ibom  ...           1.58     moderate rain
26        Yenagoa      Bayelsa  ...           0.82        light rain
27        Calabar  Cross River  ...           1.64   overcast clouds
28          Asaba        Delta  ...           1.77     moderate rain
29     Benin City          Edo  ...           1.79        light rain
30  Port Harcourt       Rivers  ...           0.85        light rain
31      Ado-Ekiti        Ekiti  ...           1.95   overcast clouds
32          Ikeja        Lagos  ...           2.57   overcast clouds
33       Abeokuta         Ogun  ...           2.69   overcast clouds
34          Akure         Ondo  ...           1.79   overcast clouds
35         Osogbo         Osun  ...           1.60   overcast clouds
36         Ibadan          Oyo  ...           2.57   overcast clouds

[37 rows x 10 columns]

Processed dataset saved successfully as weather_data.csv

Final dataset shape:
(37, 10)

ETL pipeline completed successfully.